(function () {

    App.ui.pagedata.lang("vi", {
        userOrganization: { text: "TO SOLUTIONS" },
        userBranch: { text: "Nhà máy SS" },
        userName: { text: "Taro Seisan" },
        search: { text: "Tìm kiếm" },
        show: { text: "Hiển thị" },
        calculate: { text: "Tính toán" },
        config: { text: "Thiết lập" },
        add: { text: "Thêm" },
        upd: { text: "Cập nhật" },
        clear: { text: "Xóa hiển thị" },
        copy: { text: "Sao chép" },
        del: { text: "Xóa" },
        next: { text: "Đi tiếp" },
        prev: { text: "Quay về" },
        ok: { text: "OK" },
        cancel: { text: "Hủy bỏ" },
        yes: { text: "Có" },
        no: { text: "Không" },
        execute: { text: "Thực hiện" },
        print: { text: "In" },
        excel: { text: "EXCEL" },
        shokubaExcel: { text: "EXCEL(theo bộ phận SX)" },
        output: { text: "Xuất tập tin" },
        planmake: { text: "Lập kế hoạch" },
        detail: { text: "Chi tiết" },
        meisai: { text: "Chi tiết" },
        itemCount: { text: " Kết quả" },
        colchange: { text: "Thay đổi cột" },
        end: { text: "Đóng" },
        menu: { text: "Về menu" },
        recipe: { text: "Chi tiết công thức" },
        shikakari: { text: "Sử dụng bán thành phẩm" },
        save: { text: "Lưu" },
        list: { text: "Quay về danh sách" },
        upload: { text: "Tải lên" },
        codeSearch: { text: "Tìm kiếm mã" },
        select: { text: "Chọn" },
        close: { text: "Đóng" },
        deleting: { text: "Xóa" },
        lineAdd: { text: "Thêm dòng" },
        lineDel: { text: "Xóa dòng" },
        searchCriteria: { text: "Điều kiện tìm kiếm" },
        search_configCriteria: { text: "Điều kiện tìm kiếm/Thiết lập ngày nghỉ" },
        resultList: { text: "Danh sách kết quả" },
        nowLoading: { text: "Đang xử lý…" },
        openDialog: { text: "Đang khởi động…" },
        nowListLoading: { text: "Đang xử lý {1} dữ liệu kế tiếp từ dữ liệu thứ {0}…" },
        nowValidating: { text: "Đang kiểm tra nhập…" },
        alertTitle: { text: "Có lỗi dưới đây" },
        infoTitle: { text: "Thông báo" },
        csvUpload: { text: "Đọc CSV" },
        fileName: { text: "Tên tập tin" },
        dateSrcFormat: { text: "m/d/Y" },//check this change to vn
        dateSrcFormatUS: { text: "m/d/Y" },
        dateNewFormat: { text: "d/m/Y" },
        dateNewFormatUS: { text: "m/d/Y" },
        dateMMDDFormat: { text: "d/m" },
        dateMMDDFormatUS: { text: "m/d" },
        dateDDFormat: { text: "d" },
        dateTimeNewFormat: { text: "d/m/Y H:i:s" },
        dateTimeNewFormatUS: { text: "m/d/Y H:i:s" },
        dateTimeMMDDYYHHIIFormat: { text: "d/m/Y H:i" },
        dateTimeMMDDYYHHIIFormatUS: { text: "m/d/Y H:i" },
        dateDayFormat: { text: "D" },
        dateFormat: { text: "dd/mm/yy" },
        dateFormatUS: { text: "mm/dd/yy" },
        yearMonthFormat: { text: "mm/yy" },// check this [GekkanSeihinKeikaku.aspx, GenkaIchiran.aspx, GenkaTankaSakusei.aspx]
        timeNewFormat: { text: "H:i:s" },
        login: { text: "Đăng nhập" },
        logout: { text: "Đăng xuất" },
        ari: { text: "Có" },
        nashi: { text: "Không có" },
        invalidation: { text: "Tất cả thay đổi không được lưu vì đã phát sinh lỗi sau: " },
        createdInvalidation: { text: "Dữ liệu đã tồn tại" },
        updatedDuplicate: { text: ": Nội dung đã được cập nhật bởi người dùng khác" },
        unDeletedDuplicate: { text: ": Không thể xóa dòng do người dùng khác đã cập nhật" },
        unDeletableRecord: { text: MS0688 },    
        confirmTitle: { text: "Xác nhận" },
        hinmeiIchiran: { text: "Danh sách nguyên vật liệu" },
        shizaiIchiran: { text: "Danh sách vật tư" },
        shikakariHinIchiran: { text: "Danh sách bán thành phẩm" },
        torokuIchiran: { text: "Danh sách đăng ký" },
        seihinIchiran: { text: "Danh sách sản phẩm" },
        torihikiIchiran: { text: "Danh sách nhà cung cấp" },
        genshizaiIchiran: { text: "Danh sách nguyên vật liệu" },
        menuPath: { url: "./MainMenu.aspx" },
        futaiIchiran: { text: "Danh sách kiểu đóng gói" },
        markIchiran: { text: "Danh sách mác" },
        lineIchiran: { text: "Danh sách dây chuyền" },
        checkAndReset: { text: "Chọn/Bỏ chọn toàn bộ" },
        _commonPageTitle: { text: "−FOODPROCS-Lite" },
        navigate: { text: "Di chuyển màn hình" },
        rowChange: { text: "Thay đổi dòng" },
        ma_haigo_mei: { text: "Master công thức" },
        requiredMark: { text: "*" },
        slash: { text: "/" },
        shikakariZanIchiran: { text: "Danh sách lượng tồn BTP" },

        //通貨//
        currencyJa: { text: "yen" },
        currencyZh: { text: "元" },
        currencyUs: { text: "Dollar" },
        currencyMs: { text: "RM" },
        currencyVn: { text: "đồng" },

        ///////// メッセージID定数 ////////////////
        mishiyoMessage: { text: MS0448 },
        noRecords: { text: MS0442 },
        noSelect: { text: MS0443 },
        noChange: { text: MS0444 },
        unloadWithoutSave: { text: MS0066 },
        saveConfirm: { text: MS0064 },
        findConfirm: { text: MS0065 },
        clearConfirm: { text: MS0070 },
        searchResultCount: { text: MS0006 },
        nowSaving: { text: MS0619 },
        nowProgressing: { text: MS0620 },
        successMessage: { text: MS0036 },
        duplicate: { text: MS0438 },
        searchConfirm: { text: MS0065 },
        notFound: { text: MS0037 },
        criteriaChange: { text: MS0048 },
        unprintableCheck: { text: MS0560 },
        saveComplete: { text: MS0036 },
        limitOver: { text: MS0011 },
        deleteConfirm: { text: MS0068 },
        deleteComplete: { text: MS0039 },
        hanNotExists: { text: MS0049 },
        koteiBlank: { text: MS0578 },
        overNumber: { text: MS0021 },
        deleteHanConfirm: { text: MS0313 },
        deleteAllConfirm: { text: MS0311 },
        haigoNotExists: { text: MS0366 },
        isChange: { text: MS0154 },
        beforeSearch: { text: MS0621 },
        navigateError: { text: MS0614 },
        gridChange: { text: MS0560 },
        deletedDuplicate: { text: MS0683 },
        existsError: { text: MS0289 },
        deleteShizaiConfirm: { text: MS0687 },
        overCount: { text: MS0681 },
        endCopy: { text: MS0040 },
        griddelError: { text: MS0766 },

        // メッセージ引数 //
        seizoJisseki: { text: "Thực tế sản xuất" },
        shikakariKeikaku: { text: "Kế hoạch sản xuất" },
        shikakariJisseki: { text: "Thực tế sản xuất" }

    });

})();