//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.FoodProcs.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tos.FoodProcs.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あり.
        /// </summary>
        internal static string Ari {
            get {
                return ResourceManager.GetString("Ari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ritsu_budomari.
        /// </summary>
        internal static string budomariContent {
            get {
                return ResourceManager.GetString("budomariContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分類コード.
        /// </summary>
        internal static string BunruiCode {
            get {
                return ResourceManager.GetString("BunruiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string CheckOn {
            get {
                return ResourceManager.GetString("CheckOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string ChoseiPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("ChoseiPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ChoseiRiyuKbn {
            get {
                return ResourceManager.GetString("ChoseiRiyuKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string ChoseiSaibanKbn {
            get {
                return ResourceManager.GetString("ChoseiSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 調整数.
        /// </summary>
        internal static string ChoseiSu {
            get {
                return ResourceManager.GetString("ChoseiSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コード.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string CommentPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("CommentPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string CommentSaibanKbn {
            get {
                return ResourceManager.GetString("CommentSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        internal static string CookieValue {
            get {
                return ResourceManager.GetString("CookieValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象データ：{0}.
        /// </summary>
        internal static string CsvMsgTargetData {
            get {
                return ResourceManager.GetString("CsvMsgTargetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string DateSlash {
            get {
                return ResourceManager.GetString("DateSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string DateSlashEn {
            get {
                return ResourceManager.GetString("DateSlashEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM(ddd).
        /// </summary>
        internal static string DayMonth {
            get {
                return ResourceManager.GetString("DayMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSゴシック.
        /// </summary>
        internal static string DefaultFontName {
            get {
                return ResourceManager.GetString("DefaultFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伝送待.
        /// </summary>
        internal static string DensoKbnDensoMachi {
            get {
                return ResourceManager.GetString("DensoKbnDensoMachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伝送済.
        /// </summary>
        internal static string DensoKbnDensoZumi {
            get {
                return ResourceManager.GetString("DensoKbnDensoZumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未伝送.
        /// </summary>
        internal static string DensoKbnMiDenso {
            get {
                return ResourceManager.GetString("DensoKbnMiDenso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未作成.
        /// </summary>
        internal static string DensoKbnMiSakusei {
            get {
                return ResourceManager.GetString("DensoKbnMiSakusei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ.csv.
        /// </summary>
        internal static string DownloadCsvFileName {
            get {
                return ResourceManager.GetString("DownloadCsvFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ.bat.
        /// </summary>
        internal static string DownloadFixedFileName {
            get {
                return ResourceManager.GetString("DownloadFixedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateItem.
        /// </summary>
        internal static string DuplicateItem {
            get {
                return ResourceManager.GetString("DuplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateKey.
        /// </summary>
        internal static string DuplicateKey {
            get {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string EkitaiJotaiKbn {
            get {
                return ResourceManager.GetString("EkitaiJotaiKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 999.
        /// </summary>
        internal static string ErrorCodeInt {
            get {
                return ResourceManager.GetString("ErrorCodeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーが発生しました。.
        /// </summary>
        internal static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVRXYZ.
        /// </summary>
        internal static string ExcelLineName {
            get {
                return ResourceManager.GetString("ExcelLineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists.
        /// </summary>
        internal static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの保存に失敗しました。.
        /// </summary>
        internal static string FileSaveErrorMessage {
            get {
                return ResourceManager.GetString("FileSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを保存しました。.
        /// </summary>
        internal static string FileSaveSuccessMessage {
            get {
                return ResourceManager.GetString("FileSaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルサイズが{0}MB以上です。.
        /// </summary>
        internal static string FileSizeErrorMessage {
            get {
                return ResourceManager.GetString("FileSizeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string FlagFalse {
            get {
                return ResourceManager.GetString("FlagFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string FlagTrue {
            get {
                return ResourceManager.GetString("FlagTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ○.
        /// </summary>
        internal static string FlgKyujitsuPdf {
            get {
                return ResourceManager.GetString("FlgKyujitsuPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部キー違反です.
        /// </summary>
        internal static string ForeignKeyViolation {
            get {
                return ResourceManager.GetString("ForeignKeyViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string FugoFlagAri {
            get {
                return ResourceManager.GetString("FugoFlagAri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string FugoFlagNashi {
            get {
                return ResourceManager.GetString("FugoFlagNashi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 符号出力あり.
        /// </summary>
        internal static string FugoShutsuryokuAri {
            get {
                return ResourceManager.GetString("FugoShutsuryokuAri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 風袋決定マスタ.
        /// </summary>
        internal static string FutaiKetteiMaster {
            get {
                return ResourceManager.GetString("FutaiKetteiMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合算.
        /// </summary>
        internal static string Gassan {
            get {
                return ResourceManager.GetString("Gassan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string GassanMark {
            get {
                return ResourceManager.GetString("GassanMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gekkanSeihinKeikaku.
        /// </summary>
        internal static string gekkanSeihinKeikakuCookie {
            get {
                return ResourceManager.GetString("gekkanSeihinKeikakuCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月間製品計画.
        /// </summary>
        internal static string GekkanSeihinKeikakuExcel {
            get {
                return ResourceManager.GetString("GekkanSeihinKeikakuExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月間製品計画.
        /// </summary>
        internal static string GekkanSeihinKeikakuExcelName {
            get {
                return ResourceManager.GetString("GekkanSeihinKeikakuExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string GekkanSeihinKeikakuHenkozumiCSKbn {
            get {
                return ResourceManager.GetString("GekkanSeihinKeikakuHenkozumiCSKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gekkanShikakarihinKeikaku.
        /// </summary>
        internal static string gekkanShikakarihinKeikakuCookie {
            get {
                return ResourceManager.GetString("gekkanShikakarihinKeikakuCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月間仕掛品計画.
        /// </summary>
        internal static string GekkanShikakarihinKeikakuExcelName {
            get {
                return ResourceManager.GetString("GekkanShikakarihinKeikakuExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genkaIchiran.
        /// </summary>
        internal static string genkaIchiranCookie {
            get {
                return ResourceManager.GetString("genkaIchiranCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原価一覧.
        /// </summary>
        internal static string GenkaIchiranExcel {
            get {
                return ResourceManager.GetString("GenkaIchiranExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原料注意喚起マスタ.
        /// </summary>
        internal static string GenryoChuiKankiMaster {
            get {
                return ResourceManager.GetString("GenryoChuiKankiMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genryoChuikankiMaster.
        /// </summary>
        internal static string genryoChuikankiMasterCookie {
            get {
                return ResourceManager.GetString("genryoChuikankiMasterCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原料注意喚起マスタ一覧.
        /// </summary>
        internal static string GenryoChuiKankiMasterIchiranExcel {
            get {
                return ResourceManager.GetString("GenryoChuiKankiMasterIchiranExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string GenryoHinKbn {
            get {
                return ResourceManager.GetString("GenryoHinKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秤量記録表.
        /// </summary>
        internal static string GenryoLotBangoKirokuHyoPDFName {
            get {
                return ResourceManager.GetString("GenryoLotBangoKirokuHyoPDFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genryoShiyoKeisan.
        /// </summary>
        internal static string genryoShiyoKeisanCookie {
            get {
                return ResourceManager.GetString("genryoShiyoKeisanCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 庫出依頼.
        /// </summary>
        internal static string GenryoShiyoryoKeisanExcel {
            get {
                return ResourceManager.GetString("GenryoShiyoryoKeisanExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string GenryoTorokuKbnSaiban {
            get {
                return ResourceManager.GetString("GenryoTorokuKbnSaiban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string GenryoTorokuPrefixSaiban {
            get {
                return ResourceManager.GetString("GenryoTorokuPrefixSaiban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genshizaiChoseiNyuryoku.
        /// </summary>
        internal static string genshizaiChoseiNyuryokuCookie {
            get {
                return ResourceManager.GetString("genshizaiChoseiNyuryokuCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原資材調整入力.
        /// </summary>
        internal static string GenshizaiChoseiNyuryokuExcel {
            get {
                return ResourceManager.GetString("GenshizaiChoseiNyuryokuExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原資材調整入力（期間選択）.
        /// </summary>
        internal static string GenshizaiChoseiNyuryokuExcelIkatsu {
            get {
                return ResourceManager.GetString("GenshizaiChoseiNyuryokuExcelIkatsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genshizaichoseinyuryokuExcelIkatsuDialog.
        /// </summary>
        internal static string GenshizaichoseinyuryokuExcelIkatsuDialogCookie {
            get {
                return ResourceManager.GetString("GenshizaichoseinyuryokuExcelIkatsuDialogCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenshizaiHendoHyo.
        /// </summary>
        internal static string GenshizaiHendoHyoCookie {
            get {
                return ResourceManager.GetString("GenshizaiHendoHyoCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原資材変動表.
        /// </summary>
        internal static string GenshizaiHendoHyoExcel {
            get {
                return ResourceManager.GetString("GenshizaiHendoHyoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原資材購入先マスタ.
        /// </summary>
        internal static string GenshizaiKonyusakiMaster {
            get {
                return ResourceManager.GetString("GenshizaiKonyusakiMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genshizaiKonyusakiMaster.
        /// </summary>
        internal static string genshizaiKonyusakiMasterCookie {
            get {
                return ResourceManager.GetString("genshizaiKonyusakiMasterCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原資材購入先マスタ.
        /// </summary>
        internal static string GenshizaiKonyusakiMasterExcel {
            get {
                return ResourceManager.GetString("GenshizaiKonyusakiMasterExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genshizaiShikakarihinShiyoIchiran.
        /// </summary>
        internal static string genshizaiShikakarihinShiyoIchiranCookie {
            get {
                return ResourceManager.GetString("genshizaiShikakarihinShiyoIchiranCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原資材・仕掛品使用一覧.
        /// </summary>
        internal static string GenshizaiShikakarihinShiyoIchiranExcel {
            get {
                return ResourceManager.GetString("GenshizaiShikakarihinShiyoIchiranExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genshizaiUkeharaiIchiran.
        /// </summary>
        internal static string genshizaiUkeharaiIchiranCookie {
            get {
                return ResourceManager.GetString("genshizaiUkeharaiIchiranCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原資材受払一覧.
        /// </summary>
        internal static string GenshizaiUkeharaiIchiranExcel {
            get {
                return ResourceManager.GetString("GenshizaiUkeharaiIchiranExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genshizaiZaikoNyuryoku.
        /// </summary>
        internal static string genshizaiZaikoNyuryokuCookie {
            get {
                return ResourceManager.GetString("genshizaiZaikoNyuryokuCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原資材在庫入力表.
        /// </summary>
        internal static string GenshizaiZaikoNyuryokuExcel {
            get {
                return ResourceManager.GetString("GenshizaiZaikoNyuryokuExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string GenshizaiZaikoNyuryokuHeaderRowNo {
            get {
                return ResourceManager.GetString("GenshizaiZaikoNyuryokuHeaderRowNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合計.
        /// </summary>
        internal static string GokeiText {
            get {
                return ResourceManager.GetString("GokeiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        internal static string HachuPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("HachuPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string HachuSaibanKbn {
            get {
                return ResourceManager.GetString("HachuSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string HaigoHinKbn {
            get {
                return ResourceManager.GetString("HaigoHinKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haigoMasterIchiran.
        /// </summary>
        internal static string haigoMasterIchiranCookie {
            get {
                return ResourceManager.GetString("haigoMasterIchiranCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合名マスタ.
        /// </summary>
        internal static string HaigoMasterIchiranExcel {
            get {
                return ResourceManager.GetString("HaigoMasterIchiranExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合名マスタ.
        /// </summary>
        internal static string HaigoMeiMaster {
            get {
                return ResourceManager.GetString("HaigoMeiMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合レシピマスタ.
        /// </summary>
        internal static string HaigoRecipeMaster {
            get {
                return ResourceManager.GetString("HaigoRecipeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合レシピ登録.
        /// </summary>
        internal static string HaigoRecipeMasterPdf {
            get {
                return ResourceManager.GetString("HaigoRecipeMasterPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秤マスタ.
        /// </summary>
        internal static string HakariMaster {
            get {
                return ResourceManager.GetString("HakariMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秤マスタ一覧.
        /// </summary>
        internal static string HakariMasterIchiranExcel {
            get {
                return ResourceManager.GetString("HakariMasterIchiranExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string HakariPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("HakariPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string HakariSaibanKbn {
            get {
                return ResourceManager.GetString("HakariSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string HanNoShokichi {
            get {
                return ResourceManager.GetString("HanNoShokichi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端数.
        /// </summary>
        internal static string HasuText {
            get {
                return ResourceManager.GetString("HasuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端.
        /// </summary>
        internal static string HasuTextShort {
            get {
                return ResourceManager.GetString("HasuTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hendoHyoSimulation.
        /// </summary>
        internal static string hendoHyoSimulationCookie {
            get {
                return ResourceManager.GetString("hendoHyoSimulationCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変動表シミュレーション.
        /// </summary>
        internal static string HendoHyoSimulationExcel {
            get {
                return ResourceManager.GetString("HendoHyoSimulationExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品名マスタ.
        /// </summary>
        internal static string HinmeiMaster {
            get {
                return ResourceManager.GetString("HinmeiMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hinmeiMaster.
        /// </summary>
        internal static string hinmeiMasterCookie {
            get {
                return ResourceManager.GetString("hinmeiMasterCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品名マスタ.
        /// </summary>
        internal static string HinmeiMasterIchiranExcel {
            get {
                return ResourceManager.GetString("HinmeiMasterIchiranExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更履歴確認.
        /// </summary>
        internal static string HistoryChangeExcelName {
            get {
                return ResourceManager.GetString("HistoryChangeExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HistoryChangeMaster.
        /// </summary>
        internal static string HistoryChangeMasterCookie {
            get {
                return ResourceManager.GetString("HistoryChangeMasterCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Hyphen {
            get {
                return ResourceManager.GetString("Hyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insatsuSentakuDialog.
        /// </summary>
        internal static string InsatsuSentakuDialogCookie {
            get {
                return ResourceManager.GetString("InsatsuSentakuDialogCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン権限がありません。.
        /// </summary>
        internal static string InvalidAuthoritySetting {
            get {
                return ResourceManager.GetString("InvalidAuthoritySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ形式が不正です。.
        /// </summary>
        internal static string InvalidDataFormatMessage {
            get {
                return ResourceManager.GetString("InvalidDataFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーIDまたはパスワードが違います。.
        /// </summary>
        internal static string InvalidUserIdOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserIdOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自家原料.
        /// </summary>
        internal static string Jikagenryo {
            get {
                return ResourceManager.GetString("Jikagenryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string JikaGenryoHinKbn {
            get {
                return ResourceManager.GetString("JikaGenryoHinKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.
        /// </summary>
        internal static string JissekiLotPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("JissekiLotPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string JissekiLotSaibanKbn {
            get {
                return ResourceManager.GetString("JissekiLotSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string JissekiYojitsuFlag {
            get {
                return ResourceManager.GetString("JissekiYojitsuFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重量マスタ.
        /// </summary>
        internal static string JuryoMaster {
            get {
                return ResourceManager.GetString("JuryoMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回目.
        /// </summary>
        internal static string Kaisu {
            get {
                return ResourceManager.GetString("Kaisu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定.
        /// </summary>
        internal static string Kakutei {
            get {
                return ResourceManager.GetString("Kakutei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保留品.
        /// </summary>
        internal static string kbnHoryu {
            get {
                return ResourceManager.GetString("kbnHoryu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無償.
        /// </summary>
        internal static string kbnNyukoMusho {
            get {
                return ResourceManager.GetString("kbnNyukoMusho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有償.
        /// </summary>
        internal static string kbnNyukoYusho {
            get {
                return ResourceManager.GetString("kbnNyukoYusho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 良品.
        /// </summary>
        internal static string kbnRyohin {
            get {
                return ResourceManager.GetString("kbnRyohin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告リスト.
        /// </summary>
        internal static string KeikokuListExcel {
            get {
                return ResourceManager.GetString("KeikokuListExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keikokuListSakusei.
        /// </summary>
        internal static string keikokuListSakuseiCookie {
            get {
                return ResourceManager.GetString("keikokuListSakuseiCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なし.
        /// </summary>
        internal static string KeishoNashi {
            get {
                return ResourceManager.GetString("KeishoNashi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 御中.
        /// </summary>
        internal static string KeishoOnchu {
            get {
                return ResourceManager.GetString("KeishoOnchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 様.
        /// </summary>
        internal static string KeishoSama {
            get {
                return ResourceManager.GetString("KeishoSama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keys.
        /// </summary>
        internal static string Keys {
            get {
                return ResourceManager.GetString("Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string KotaiJotaiKbn {
            get {
                return ResourceManager.GetString("KotaiJotaiKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小分けラベル発行トラン.
        /// </summary>
        internal static string KowakeLabelTran {
            get {
                return ResourceManager.GetString("KowakeLabelTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string KowakeLotPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("KowakeLotPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string KowakeLotSaibanKbn {
            get {
                return ResourceManager.GetString("KowakeLotSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小分け実績トラン.
        /// </summary>
        internal static string KowakeTran {
            get {
                return ResourceManager.GetString("KowakeTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 庫場所コード.
        /// </summary>
        internal static string KurabashoCode {
            get {
                return ResourceManager.GetString("KurabashoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 庫場所マスタ.
        /// </summary>
        internal static string KurabashoMaster {
            get {
                return ResourceManager.GetString("KurabashoMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 繰越残.
        /// </summary>
        internal static string KurikoshiZan {
            get {
                return ResourceManager.GetString("KurikoshiZan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string KyujitsuRiyuKbn {
            get {
                return ResourceManager.GetString("KyujitsuRiyuKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ラベル出力あり.
        /// </summary>
        internal static string LabelHakkouAri {
            get {
                return ResourceManager.GetString("LabelHakkouAri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string LangEn {
            get {
                return ResourceManager.GetString("LangEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string LangEnUs {
            get {
                return ResourceManager.GetString("LangEnUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        internal static string LangJa {
            get {
                return ResourceManager.GetString("LangJa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vi.
        /// </summary>
        internal static string LangVi {
            get {
                return ResourceManager.GetString("LangVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh.
        /// </summary>
        internal static string LangZh {
            get {
                return ResourceManager.GetString("LangZh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ラインマスタ.
        /// </summary>
        internal static string LineMaster {
            get {
                return ResourceManager.GetString("LineMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}行目.
        /// </summary>
        internal static string LineUnit {
            get {
                return ResourceManager.GetString("LineUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string MarkCodeSpice {
            get {
                return ResourceManager.GetString("MarkCodeSpice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未使用.
        /// </summary>
        internal static string Mishiyo {
            get {
                return ResourceManager.GetString("Mishiyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未.
        /// </summary>
        internal static string MishiyoShort {
            get {
                return ResourceManager.GetString("MishiyoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string MonthCount {
            get {
                return ResourceManager.GetString("MonthCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd(ddd).
        /// </summary>
        internal static string MonthDay {
            get {
                return ResourceManager.GetString("MonthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string MonthDayCount {
            get {
                return ResourceManager.GetString("MonthDayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}データに該当のデータが存在するため削除できません。(MS0001).
        /// </summary>
        internal static string MS0001 {
            get {
                return ResourceManager.GetString("MS0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同一データが存在します。(MS0027).
        /// </summary>
        internal static string MS0027 {
            get {
                return ResourceManager.GetString("MS0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の入力は必須です。(MS0042).
        /// </summary>
        internal static string MS0042 {
            get {
                return ResourceManager.GetString("MS0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が重複しています。(MS0045).
        /// </summary>
        internal static string MS0045 {
            get {
                return ResourceManager.GetString("MS0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定された{0}は存在しません。(MS0049).
        /// </summary>
        internal static string MS0049 {
            get {
                return ResourceManager.GetString("MS0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コード：{0}は製造可能ラインとして登録されています。%n削除できません。(MS0297).
        /// </summary>
        internal static string MS0297 {
            get {
                return ResourceManager.GetString("MS0297", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}計画が存在する為、削除できません。(MS0452).
        /// </summary>
        internal static string MS0452 {
            get {
                return ResourceManager.GetString("MS0452", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の風袋決定データは1件以上必要なため削除できません。(MS0577).
        /// </summary>
        internal static string MS0577 {
            get {
                return ResourceManager.GetString("MS0577", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合コード、有効日付が重複するデータが存在しています。(MS0622).
        /// </summary>
        internal static string MS0622 {
            get {
                return ResourceManager.GetString("MS0622", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}～{2}の範囲内にして下さい。(MS0666).
        /// </summary>
        internal static string MS0666 {
            get {
                return ResourceManager.GetString("MS0666", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効日付が他の版と重なる為、保存できません。(MS0691).
        /// </summary>
        internal static string MS0691 {
            get {
                return ResourceManager.GetString("MS0691", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕掛品に対する製造可能ラインデータが存在しないため登録出来ません。データを確認してください。 製造日：{0}  コード：{1}  (MS0707).
        /// </summary>
        internal static string MS0707 {
            get {
                return ResourceManager.GetString("MS0707", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ形式が不正です。項目の数が違います。　対象データ：{0} (MS0735).
        /// </summary>
        internal static string MS0735 {
            get {
                return ResourceManager.GetString("MS0735", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実績が確定済みのため、{0}できません。　対象のロット番号：{1} (MS0743).
        /// </summary>
        internal static string MS0743 {
            get {
                return ResourceManager.GetString("MS0743", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索日付とＣＳＶの日付が一致していません。(MS0767).
        /// </summary>
        internal static string MS0767 {
            get {
                return ResourceManager.GetString("MS0767", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他のユーザーにより内容が変更されているため更新できません。再検索を行い、データを更新してください。(MS0823).
        /// </summary>
        internal static string MS0823 {
            get {
                return ResourceManager.GetString("MS0823", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なし.
        /// </summary>
        internal static string Nashi {
            get {
                return ResourceManager.GetString("Nashi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string NashiKeishoKbn {
            get {
                return ResourceManager.GetString("NashiKeishoKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 明細.
        /// </summary>
        internal static string nm_meisai {
            get {
                return ResourceManager.GetString("nm_meisai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 集計.
        /// </summary>
        internal static string nm_shukeiKbn {
            get {
                return ResourceManager.GetString("nm_shukeiKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string No_seq {
            get {
                return ResourceManager.GetString("No_seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルが指定されていません。(MS0663).
        /// </summary>
        internal static string NoFileAttachmentMessage {
            get {
                return ResourceManager.GetString("NoFileAttachmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データが存在しません。(MS0058).
        /// </summary>
        internal static string NoFileDataMessage {
            get {
                return ResourceManager.GetString("NoFileDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納入依頼書.
        /// </summary>
        internal static string NonyuIraishoPdf {
            get {
                return ResourceManager.GetString("NonyuIraishoPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        internal static string NonyuIraishoPdfAddition {
            get {
                return ResourceManager.GetString("NonyuIraishoPdfAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ）.
        /// </summary>
        internal static string NonyuIraishoPdfBracketEnd {
            get {
                return ResourceManager.GetString("NonyuIraishoPdfBracketEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （.
        /// </summary>
        internal static string NonyuIraishoPdfBracketStart {
            get {
                return ResourceManager.GetString("NonyuIraishoPdfBracketStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string NonyuIraishoPdfCancel {
            get {
                return ResourceManager.GetString("NonyuIraishoPdfCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更.
        /// </summary>
        internal static string NonyuIraishoPdfChange {
            get {
                return ResourceManager.GetString("NonyuIraishoPdfChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        internal static string NonyuIraishoPdfDelete {
            get {
                return ResourceManager.GetString("NonyuIraishoPdfDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分類.
        /// </summary>
        internal static string NonyuIraishoPdfItemNameBunrui {
            get {
                return ResourceManager.GetString("NonyuIraishoPdfItemNameBunrui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品名コード.
        /// </summary>
        internal static string NonyuIraishoPdfItemNameHinCode {
            get {
                return ResourceManager.GetString("NonyuIraishoPdfItemNameHinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品名.
        /// </summary>
        internal static string NonyuIraishoPdfItemNameHinmei {
            get {
                return ResourceManager.GetString("NonyuIraishoPdfItemNameHinmei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 荷姿.
        /// </summary>
        internal static string NonyuIraishoPdfItemNameNisugata {
            get {
                return ResourceManager.GetString("NonyuIraishoPdfItemNameNisugata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単位：.
        /// </summary>
        internal static string NonyuIraishoPdfItemNameTani {
            get {
                return ResourceManager.GetString("NonyuIraishoPdfItemNameTani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string NonyuIraishoPrintTypeAllPrint {
            get {
                return ResourceManager.GetString("NonyuIraishoPrintTypeAllPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string NonyuIraishoPrintTypeSelectAllPrint {
            get {
                return ResourceManager.GetString("NonyuIraishoPrintTypeSelectAllPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納入実績.
        /// </summary>
        internal static string NonyuJisseki {
            get {
                return ResourceManager.GetString("NonyuJisseki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string NonyuPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("NonyuPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string NonyuSaibanKbn {
            get {
                return ResourceManager.GetString("NonyuSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納入数量.
        /// </summary>
        internal static string NonyuSuryo {
            get {
                return ResourceManager.GetString("NonyuSuryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string NonyuSuryoNonyushoKeishikiKbn {
            get {
                return ResourceManager.GetString("NonyuSuryoNonyushoKeishikiKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納入単位.
        /// </summary>
        internal static string NonyuTani {
            get {
                return ResourceManager.GetString("NonyuTani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納入予定.
        /// </summary>
        internal static string NonyuYotei {
            get {
                return ResourceManager.GetString("NonyuYotei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonyuYoteiListSakusei.
        /// </summary>
        internal static string nonyuYoteiListSakuseiCookie {
            get {
                return ResourceManager.GetString("nonyuYoteiListSakuseiCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納入予定リスト.
        /// </summary>
        internal static string NonyuYoteiListSakuseiExcel {
            get {
                return ResourceManager.GetString("NonyuYoteiListSakuseiExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未選択.
        /// </summary>
        internal static string NoSelectConditionExcel {
            get {
                return ResourceManager.GetString("NoSelectConditionExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csvファイル、もしくは txtファイルを選択してください。.
        /// </summary>
        internal static string NotCSVFileMessage {
            get {
                return ResourceManager.GetString("NotCSVFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotExsists.
        /// </summary>
        internal static string NotExsists {
            get {
                return ResourceManager.GetString("NotExsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL は許可されません。.
        /// </summary>
        internal static string NotNullAllow {
            get {
                return ResourceManager.GetString("NotNullAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string OnchuKeishoKbn {
            get {
                return ResourceManager.GetString("OnchuKeishoKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同時実行エラーです。.
        /// </summary>
        internal static string OptimisticConcurrencyError {
            get {
                return ResourceManager.GetString("OptimisticConcurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pdf.
        /// </summary>
        internal static string pdfExtens {
            get {
                return ResourceManager.GetString("pdfExtens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用先なし.
        /// </summary>
        internal static string PdfMishiyoComment {
            get {
                return ResourceManager.GetString("PdfMishiyoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数製品で使用.
        /// </summary>
        internal static string PdfSeihinInfoComment {
            get {
                return ResourceManager.GetString("PdfSeihinInfoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string persentKanzan {
            get {
                return ResourceManager.GetString("persentKanzan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プライマリキー制約違反です。.
        /// </summary>
        internal static string PrimaryKeyViolation {
            get {
                return ResourceManager.GetString("PrimaryKeyViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルアップロード処理中にサーバーで不明なエラーが発生しました。システム管理者に問い合わせしてください。.
        /// </summary>
        internal static string RaiseFileUploadServerError {
            get {
                return ResourceManager.GetString("RaiseFileUploadServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string RiyuKaijoKbn {
            get {
                return ResourceManager.GetString("RiyuKaijoKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no_saiban.
        /// </summary>
        internal static string saibanNoContent {
            get {
                return ResourceManager.GetString("saibanNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string SamaKeishoKbn {
            get {
                return ResourceManager.GetString("SamaKeishoKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 順位が重複しています。.
        /// </summary>
        internal static string sameJuni {
            get {
                return ResourceManager.GetString("sameJuni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SecondKaisoSu {
            get {
                return ResourceManager.GetString("SecondKaisoSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製品ロット番号.
        /// </summary>
        internal static string SeihinLotNumber {
            get {
                return ResourceManager.GetString("SeihinLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string SeihinLotPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("SeihinLotPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string SeihinLotSaibanKbn {
            get {
                return ResourceManager.GetString("SeihinLotSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正規.
        /// </summary>
        internal static string SeikiText {
            get {
                return ResourceManager.GetString("SeikiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正.
        /// </summary>
        internal static string SeikiTextShort {
            get {
                return ResourceManager.GetString("SeikiTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製造.
        /// </summary>
        internal static string Seizo {
            get {
                return ResourceManager.GetString("Seizo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製造実績数.
        /// </summary>
        internal static string SeizoJisseki {
            get {
                return ResourceManager.GetString("SeizoJisseki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製造ラインマスタ.
        /// </summary>
        internal static string SeizoLineMaster {
            get {
                return ResourceManager.GetString("SeizoLineMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string SeizomotoTorihikisakiKbn {
            get {
                return ResourceManager.GetString("SeizomotoTorihikisakiKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeizoNippo.
        /// </summary>
        internal static string SeizoNippoCookie {
            get {
                return ResourceManager.GetString("SeizoNippoCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製造日報.
        /// </summary>
        internal static string SeizoNippoExcel {
            get {
                return ResourceManager.GetString("SeizoNippoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製造予定数.
        /// </summary>
        internal static string SeizoYotei {
            get {
                return ResourceManager.GetString("SeizoYotei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択.
        /// </summary>
        internal static string SelectConditionExcel {
            get {
                return ResourceManager.GetString("SelectConditionExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string SelectLotNashi {
            get {
                return ResourceManager.GetString("SelectLotNashi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SelectLotOya {
            get {
                return ResourceManager.GetString("SelectLotOya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string SelectLotSeihin {
            get {
                return ResourceManager.GetString("SelectLotSeihin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string SelectLotShikakari {
            get {
                return ResourceManager.GetString("SelectLotShikakari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サービスでエラーが発生しました。.
        /// </summary>
        internal static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実行不能なエラーが発生しました。担当者に連絡してください。.
        /// </summary>
        internal static string ServiceErrorForClient {
            get {
                return ResourceManager.GetString("ServiceErrorForClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設備コード.
        /// </summary>
        internal static string SetsubiCode {
            get {
                return ResourceManager.GetString("SetsubiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設備マスタ.
        /// </summary>
        internal static string SetsubiMaster {
            get {
                return ResourceManager.GetString("SetsubiMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ShiiresakiTorihikisakiKbn {
            get {
                return ResourceManager.GetString("ShiiresakiTorihikisakiKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕掛品.
        /// </summary>
        internal static string ShikakariHin {
            get {
                return ResourceManager.GetString("ShikakariHin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string ShikakarihinJotaiKbn {
            get {
                return ResourceManager.GetString("ShikakarihinJotaiKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string ShikakariHinKbn {
            get {
                return ResourceManager.GetString("ShikakariHinKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        internal static string ShikakarihinKeikakuPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("ShikakarihinKeikakuPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string ShikakarihinKeikakuSaibanKbn {
            get {
                return ResourceManager.GetString("ShikakarihinKeikakuSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕掛品使用一覧表.
        /// </summary>
        internal static string ShikakarihinShiyoIchiran {
            get {
                return ResourceManager.GetString("ShikakarihinShiyoIchiran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string ShikakariLotPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("ShikakariLotPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string ShikakariLotSaibanKbn {
            get {
                return ResourceManager.GetString("ShikakariLotSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合チェック表.
        /// </summary>
        internal static string ShikomiCheckHyoPDFName {
            get {
                return ResourceManager.GetString("ShikomiCheckHyoPDFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕込計画表.
        /// </summary>
        internal static string ShikomiKeikakuHyo {
            get {
                return ResourceManager.GetString("ShikomiKeikakuHyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shikomiNippo.
        /// </summary>
        internal static string shikomiNippoCookie {
            get {
                return ResourceManager.GetString("shikomiNippoCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕込日報.
        /// </summary>
        internal static string ShikomiNippoExcel {
            get {
                return ResourceManager.GetString("ShikomiNippoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to しない.
        /// </summary>
        internal static string Shinai {
            get {
                return ResourceManager.GetString("Shinai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用.
        /// </summary>
        internal static string Shiyo {
            get {
                return ResourceManager.GetString("Shiyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用実績.
        /// </summary>
        internal static string ShiyoJisseki {
            get {
                return ResourceManager.GetString("ShiyoJisseki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用数量.
        /// </summary>
        internal static string ShiyoSuryo {
            get {
                return ResourceManager.GetString("ShiyoSuryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string ShiyoSuryoNonyushoKeishikiKbn {
            get {
                return ResourceManager.GetString("ShiyoSuryoNonyushoKeishikiKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string ShiyoYojitsuSeqNoPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("ShiyoYojitsuSeqNoPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string ShiyoYojitsuSeqNoSaibanKbn {
            get {
                return ResourceManager.GetString("ShiyoYojitsuSeqNoSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用予定.
        /// </summary>
        internal static string ShiyoYotei {
            get {
                return ResourceManager.GetString("ShiyoYotei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資材使用データ.
        /// </summary>
        internal static string ShizaiShiyoData {
            get {
                return ResourceManager.GetString("ShizaiShiyoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資材使用マスタ.
        /// </summary>
        internal static string ShizaiShiyoMaster {
            get {
                return ResourceManager.GetString("ShizaiShiyoMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資材使用マスタボディ.
        /// </summary>
        internal static string ShizaiShiyoMasterBody {
            get {
                return ResourceManager.GetString("ShizaiShiyoMasterBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資材使用マスタヘッダー.
        /// </summary>
        internal static string ShizaiShiyoMasterHeader {
            get {
                return ResourceManager.GetString("ShizaiShiyoMasterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資材使用量計算.
        /// </summary>
        internal static string ShizaiShiyoryoKeisanExcel {
            get {
                return ResourceManager.GetString("ShizaiShiyoryoKeisanExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shokubaDialog.
        /// </summary>
        internal static string shokubaDialogCookie {
            get {
                return ResourceManager.GetString("shokubaDialogCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕込職場.
        /// </summary>
        internal static string ShokubaSentakuShikomiName {
            get {
                return ResourceManager.GetString("ShokubaSentakuShikomiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ShokubaSentakuShikomiValue {
            get {
                return ResourceManager.GetString("ShokubaSentakuShikomiValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用職場.
        /// </summary>
        internal static string ShokubaSentakuShiyoName {
            get {
                return ResourceManager.GetString("ShokubaSentakuShiyoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ShokubaSentakuShiyoValue {
            get {
                return ResourceManager.GetString("ShokubaSentakuShiyoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 処理品.
        /// </summary>
        internal static string Shorihin {
            get {
                return ResourceManager.GetString("Shorihin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string ShukkoKbn {
            get {
                return ResourceManager.GetString("ShukkoKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 倉庫.
        /// </summary>
        internal static string Soko {
            get {
                return ResourceManager.GetString("Soko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string SonotaJotaiKbn {
            get {
                return ResourceManager.GetString("SonotaJotaiKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string StringSpace {
            get {
                return ResourceManager.GetString("StringSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 済.
        /// </summary>
        internal static string Sumi {
            get {
                return ResourceManager.GetString("Sumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to する.
        /// </summary>
        internal static string Suru {
            get {
                return ResourceManager.GetString("Suru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象.
        /// </summary>
        internal static string Taisho {
            get {
                return ResourceManager.GetString("Taisho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象外.
        /// </summary>
        internal static string Taishogai {
            get {
                return ResourceManager.GetString("Taishogai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string TaniCodeG {
            get {
                return ResourceManager.GetString("TaniCodeG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string TaniCodeKg {
            get {
                return ResourceManager.GetString("TaniCodeKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string TaniCodeL {
            get {
                return ResourceManager.GetString("TaniCodeL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LB.
        /// </summary>
        internal static string TaniCodeLB {
            get {
                return ResourceManager.GetString("TaniCodeLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ｇ.
        /// </summary>
        internal static string TaniGram {
            get {
                return ResourceManager.GetString("TaniGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投入状況トラン.
        /// </summary>
        internal static string TonyuJyokyoTran {
            get {
                return ResourceManager.GetString("TonyuJyokyoTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投入トラン.
        /// </summary>
        internal static string TonyuTran {
            get {
                return ResourceManager.GetString("TonyuTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先コード.
        /// </summary>
        internal static string TorihikisakiCode {
            get {
                return ResourceManager.GetString("TorihikisakiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to torihikisakiMaster.
        /// </summary>
        internal static string torihikisakiMasterCookie {
            get {
                return ResourceManager.GetString("torihikisakiMasterCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先マスタ一覧.
        /// </summary>
        internal static string TorihikisakiMasterIchiranExcel {
            get {
                return ResourceManager.GetString("TorihikisakiMasterIchiranExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製造元.
        /// </summary>
        internal static string TorihikisakiSeizomoto {
            get {
                return ResourceManager.GetString("TorihikisakiSeizomoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕入先.
        /// </summary>
        internal static string TorihikisakiShiiresaki {
            get {
                return ResourceManager.GetString("TorihikisakiShiiresaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 売上元.
        /// </summary>
        internal static string TorihikisakiUriagemoto {
            get {
                return ResourceManager.GetString("TorihikisakiUriagemoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一部未登録.
        /// </summary>
        internal static string TorokuKbnIchibuMiToroku {
            get {
                return ResourceManager.GetString("TorokuKbnIchibuMiToroku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未登録.
        /// </summary>
        internal static string TorokuKbnMiToroku {
            get {
                return ResourceManager.GetString("TorokuKbnMiToroku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録済.
        /// </summary>
        internal static string TorokuKbnTorokuSumi {
            get {
                return ResourceManager.GetString("TorokuKbnTorokuSumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合計金額.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 調整数.
        /// </summary>
        internal static string UkeharaiKbnChoseiSu {
            get {
                return ResourceManager.GetString("UkeharaiKbnChoseiSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納入実績.
        /// </summary>
        internal static string UkeharaiKbnNonyuJisseki {
            get {
                return ResourceManager.GetString("UkeharaiKbnNonyuJisseki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納入予定.
        /// </summary>
        internal static string UkeharaiKbnNonyuYotei {
            get {
                return ResourceManager.GetString("UkeharaiKbnNonyuYotei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製造実績.
        /// </summary>
        internal static string UkeharaiKbnSeizoJisseki {
            get {
                return ResourceManager.GetString("UkeharaiKbnSeizoJisseki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製造予定.
        /// </summary>
        internal static string UkeharaiKbnSeizoYotei {
            get {
                return ResourceManager.GetString("UkeharaiKbnSeizoYotei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用実績.
        /// </summary>
        internal static string UkeharaiKbnShiyoJisseki {
            get {
                return ResourceManager.GetString("UkeharaiKbnShiyoJisseki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用予定.
        /// </summary>
        internal static string UkeharaiKbnShiyoYotei {
            get {
                return ResourceManager.GetString("UkeharaiKbnShiyoYotei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnDeletableRecord.
        /// </summary>
        internal static string UnDeletableRecord {
            get {
                return ResourceManager.GetString("UnDeletableRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他のテーブルで使用しているため、削除できません。(MS0659).
        /// </summary>
        internal static string UnDeletableRecordMessage {
            get {
                return ResourceManager.GetString("UnDeletableRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string UriagemotoTorihikisakiKbn {
            get {
                return ResourceManager.GetString("UriagemotoTorihikisakiKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} が [{1}] のデータはすでに登録されています。(MS0660).
        /// </summary>
        internal static string ValidationDataFoundMessage {
            get {
                return ResourceManager.GetString("ValidationDataFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} が [{1}] のデータが見つかりません。(MS0661).
        /// </summary>
        internal static string ValidationDataNotFoundMessage {
            get {
                return ResourceManager.GetString("ValidationDataNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一意キー制約違反です。(MS0662).
        /// </summary>
        internal static string ValidationKey {
            get {
                return ResourceManager.GetString("ValidationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy/MM.
        /// </summary>
        internal static string YearMonth {
            get {
                return ResourceManager.GetString("YearMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string YoteiYojitsuFlag {
            get {
                return ResourceManager.GetString("YoteiYojitsuFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 残実績トラン.
        /// </summary>
        internal static string ZanJissekiTran {
            get {
                return ResourceManager.GetString("ZanJissekiTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string ZanLabelLotPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("ZanLabelLotPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string ZanLabelLotSaibanKbn {
            get {
                return ResourceManager.GetString("ZanLabelLotSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string ZanLotPrefixSaibanKbn {
            get {
                return ResourceManager.GetString("ZanLotPrefixSaibanKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string ZanLotSaibanKbn {
            get {
                return ResourceManager.GetString("ZanLotSaibanKbn", resourceCulture);
            }
        }
    }
}
