SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IDX_SeihinJissekiTrace_select] ON [dbo].[tr_tonyu]
(
	[no_lot_seihin] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO